CREATE DATABASE DB_PEDIDOS;

USE DB_PEDIDOS;

DROP TABLE PRODUTOS;
DROP TABLE PEDIDOS;
DROP TABLE USUARIOS;

CREATE TABLE PEDIDOS(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    STATUS VARCHAR(10) NOT NULL,
    ID_CLIENTE INT NOT NULL
);

CREATE TABLE PRODUTOS(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    SKU VARCHAR(20) NOT NULL,
    QUANTIDADE INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID) ON DELETE CASCADE
);

CREATE TABLE USUARIOS(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    LOGIN VARCHAR(20) UNIQUE NOT NULL,
    SENHA VARCHAR(20) NOT NULL
);

INSERT INTO PEDIDOS (STATUS, ID_CLIENTE) VALUES ('ABERTO', 1);
INSERT INTO PEDIDOS (STATUS, ID_CLIENTE) VALUES ('ABERTO', 2);
INSERT INTO PRODUTOS (SKU, QUANTIDADE, ID_PEDIDO) VALUES ('CELNVIPHONE12', 1, 1);
INSERT INTO PRODUTOS (SKU, QUANTIDADE, ID_PEDIDO) VALUES ('PELNVIPHONE12', 2, 1);
INSERT INTO PRODUTOS (SKU, QUANTIDADE, ID_PEDIDO) VALUES ('FONUSSAMSUNG', 1, 1);
INSERT INTO PRODUTOS (SKU, QUANTIDADE, ID_PEDIDO) VALUES ('CELNVIPHONE12', 3, 2);
INSERT INTO USUARIOS (LOGIN, SENHA) VALUES ('ADMIN', 'ADMIN');